#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: PR Checks

on:
  pull_request:
    branches: 
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Shellcheck
        run: |
          find . -type f -name '*.sh' | wc -l
          find . -type f -name '*.sh' | xargs shellcheck --external-sources

  digest-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script which checks container image digest
      run: |
        sudo pip install yq
        /bin/bash .ci/devfile-images-check.sh

  nightly-build-publish:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64,arm64,ppc64le,s390x]
    outputs:
      amd64: ${{ steps.result.outputs.amd64 }}
      arm64: ${{ steps.result.outputs.arm64 }}
      ppc64le: ${{ steps.result.outputs.ppc64le }}
      s390x: ${{ steps.result.outputs.s390x }}
    steps:
      -
        name: "Checkout Che Dashboard source code"
        uses: actions/checkout@v2
      - 
        name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          # VERSION file contains 7.yy.0-SNAPSHOT but for nightlies we want just a nightly tag
          # VERSION=$(head -n 1 VERSION)
          # echo ::set-output name=version::${VERSION}
          PLATFORMS=$(cat PLATFORMS)
          echo ::set-output name=platforms::${PLATFORMS}
      -
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      -
        name: "Set up Docker Buildx ${{ matrix.arch }}"
        uses: docker/setup-buildx-action@v1
      - name: Cache docker layers
        uses: actions/cache@v1
        with:
          path: ./caches
          key: v1-${{ github.head_ref }}
 
      - name: Load docker layer cache
        run: |
          set +o pipefail
          docker load -i ./caches/app.tar | true
      -
        name: "Docker quay.io Login"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - 
        name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build devfile registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          target: registry
          platforms: linux/${{ matrix.arch }}
          tags: app-${{ matrix.arch }}
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache"
          push: false
    
      - name: Build offline devfile registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          target: offline-registry
          platforms: linux/${{ matrix.arch }}
          tags: app-${{ matrix.arch }}
          cache-from: "type=local,src=/tmp/.buildx-cache"
          push: false
